### ISSUE TITLE
Inventory tweaks

### ISSUE THREAD

**Issue by SVinxce** [JF-Dunford/Space-Gorilla#10]
**Is your feature request related to a problem? Please describe.**
Having chests as early storage can make things very unorganised if they are not sorted properly. This is something that probably annoyes a lot of players. 
**Describe the solution you'd like**
I 'd like to request the addition of Inventory tweaks to fulfill our global needs of inventory 

**Additional context**
This is a post after a conversation between hippo and me on 15 november

**Comment by HippocraticOath** [comment]
Added in next update
