### ISSUE TITLE
No way to get other seeds than Better with Mods hemp

### ISSUE THREAD

**Issue by SVinxce** [JF-Dunford/Space-Gorilla#14]
**Is your feature request related to a problem? Please describe.**
Better with mods cuts out the possibility to get seeds, other than melon/pumpkin and its own hemp. Which makes it hard to produce a decent amount plant oil (IE) in a decently quick and efficient way. This is due to the Industrial Hemp seeds producing 1.5x more plant oil in the squeezer than the next best, the vanilla wheat seeds (which are also pretty much unavailable from everything I have tried to do to get them).

**Describe the solution you'd like**
Either enable a way to get Industrial Hemp or make BwM's hemp compatible with IE to produce plant oil.

**Comment by HippocraticOath** [comment]
As a side note, wheat can be found in the overworld, but it is very rare. The easiest way would be to purchase some from Pam's Market.

**Comment by HippocraticOath** [comment]
BWM's Hemp Seeds can now be used in place of IE's Industrial Hemp seeds in the next update.
