### ISSUE TITLE
Tinker's tool leveling

### ISSUE THREAD

**Issue by SVinxce** [JF-Dunford/Space-Gorilla#16]
**Is your feature request related to a problem? Please describe.**
I find that 3 modifiers for your tool in Tinker's is not quite enough for the amount I use them.

**Describe the solution you'd like**
Tinker's tool leveling adds the functionality that you become more and more used to your tools, which gives more space for modifiers. This results in your tools being better and makes you want to keep them for longer, it makes them have a much bigger value then just being a tool.

**Comment by HippocraticOath** [comment]
I am worried Tinker's Tool Leveling will completely out-perform anything provided in any of the later stage mods. Let's keep pushing forward before a decision is made.
