### ISSUE TITLE
Iron duplication in changed recipes

### ISSUE THREAD

**Issue by SVinxce** [JF-Dunford/Space-Gorilla#17]
**Describe the bug**
Items that use nuggets instead of ingots for crafting (example bucket/compass - changed recipes), produce the vanilla ingot amount after smelting in the tinker's smeltry.

**To Reproduce**
1. Make bucket out of 7 iron nuggets / compass out of 4 nuggets
2. drop bucket / compass in smeltry
3. wait for the items to smelt
4. get respectivly 3 / 4 ingots out

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12463771/69666222-33475480-108c-11ea-952f-7f3e86ca21d9.png)

![image](https://user-images.githubusercontent.com/12463771/69666246-3cd0bc80-108c-11ea-98f1-b905e54be097.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HippocraticOath** [comment]
Fixed in next update.
