### ISSUE TITLE
Achievments/progression - Tools step appeared twice

### ISSUE THREAD

**Issue by SVinxce** [JF-Dunford/Space-Gorilla#4]
**Is your feature request related to a problem? Please describe.**
It is not a real issue, it's more of a quick remark that there is one progression step / achievment that is placed twice, for some reason (below a screenshot)
![2019-11-13_21 59 41](https://user-images.githubusercontent.com/12463771/68804238-920ad800-0661-11ea-9e80-77b3fe0271b6.png)

Also, could we add quick leaf decay? It makes taking down trees quite a bit easier/quicker

**Comment by HippocraticOath** [comment]
Known bug, just ignore the insubstantial advancement "Tutorial" tree for now. It has some redundant advancements that were merged with the next stage for simplicity. This will be changed in the next update.

**Comment by HippocraticOath** [comment]
Also - quick leaf decay in consideration

**Comment by HippocraticOath** [comment]
"Tutorial" advancement page removed in 0.2.0
Quick leaf decay added in 0.2.0
