### ISSUE TITLE
Not vanilla wood recipes "boat"

### ISSUE THREAD

**Issue by ArneADM** [JF-Dunford/Space-Gorilla#6]
**Describe the bug**
You can use vanilla recipes that you are still able to use by using non-vanilla wood.

**To Reproduce**
1. Collect non-vanilla wood
2. Try and do the vanilla recipes 
3. Enjoy

**Expected behavior**
I expect it to work with other recipes, but found the problem with boats.

**Screenshots**

<img width="720" alt="Schermafbeelding 2019-11-14 om 15 36 35" src="https://user-images.githubusercontent.com/57421414/68883830-19178900-0712-11ea-9b0e-0c25cc9ab135.png">

**Comment by HippocraticOath** [comment]
Also including doors with this

**Comment by HippocraticOath** [comment]
Recipes changed for next update.
