### ISSUE TITLE
Construct's armory

### ISSUE THREAD

**Issue by SVinxce** [JF-Dunford/Space-Gorilla#7]
Would it be possible to add construct's armory? It is a Tinker's add-on to make custom armor sets just like you would with your tools :) 
I think it would fit the theme with tinker's :)

**Comment by HippocraticOath** [comment]
You might know the answer to this - will Construct's Armory outshine Modular Powersuits at any point?

**Comment by SVinxce** [comment]
Well early-game, untill you have advanced enough to get to modular powersuites, it outshines everything. It is as customiseable as the normal tinker's tools, gives you buffs depending on the material properties etc. In my humble opinion, it would benefit the middlestage very well (and it might even save us from dying this much xD).

**Comment by HippocraticOath** [comment]
Added in next update.
